main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('properties/<str:slug>/', detailedview, name='detailedview'),
    path('property-view-booking/', booking, name='booking'),
    path('property-for-rent/', rent, name='rent'),
    path('property-for-sale/', sale, name='sale'),
    path('land-for-sale/', land, name='land'),
    path('contact-us/', contact, name='contact'),
    path('about-us/', about, name='about'),
    path('list-your-property/', listing, name='listing'),
    path('properties-search/', search, name='search'),
]

property/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

admin.site.site_header = 'Rolproperties admin'
admin.site.site_title = 'Rolproperties admin'
admin.site.index_title = 'Rolproperties administration'

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from autoslug import AutoSlugField


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Listings(models.Model):
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='name')
    email = models.EmailField(max_length=30)
    address = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    category = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    date_posted = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


CATEGORIES = (
    ("Sale", "Sale"),
    ("Rent", "Rent"),
    ("Lease", "Lease"),
)

UNITS = (
    (" ", "No Units"),
    ("K", "K"),
    ("M", "M"),

)


class Property(models.Model):
    '''property model'''
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='name', unique=True)
    seller = models.CharField(default="Seller", max_length=100)
    date_posted = models.DateField(auto_now_add=True)
    rooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    bedrooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    bathrooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    sqfts = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    size = models.CharField(default="For Land only", max_length=100, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="properties")
    type_for = models.CharField(choices=CATEGORIES, max_length=10)
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE, related_name="properties")
    price = models.IntegerField()
    price_units = models.CharField(max_length=10, choices=UNITS)
    short_description = models.CharField(max_length=60)
    description = models.TextField()
    featured = models.BooleanField(default=False)
    image_1 = models.ImageField(upload_to="images")
    image_2 = models.ImageField(upload_to="images")
    image_3 = models.ImageField(upload_to="images")
    image_4 = models.ImageField(upload_to="images")
    image_5 = models.ImageField(upload_to="images")
    image_6 = models.ImageField(upload_to="images")

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=50)
    message = models.TextField(max_length=255)
    date_posted = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name


class Booking(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    location = models.CharField(max_length=50)
    date_posted = models.DateField(auto_now_add=True)
    propert = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name="properties")

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import *

# Create your views here.


def index(request):
    if request.method == "GET":
        # try:
        posts = Property.objects.all()[:6]
        slides = Property.objects.filter(featured=True)[:3]
        context = {
            "posts": posts,
            "slides": slides,
        }
        return render(request, 'main/nav/home.html', context)
        # except:
        #     messages.error(
        #         request, 'Something went wrong, kindly try again!!!')
        #     return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def detailedview(request, slug):
    if request.method == "GET":
        try:
            post = Property.objects.get(slug=slug)
            context = {
                "post": post,
            }

            return render(request, 'main/incl/details.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")

    else:
        return HttpResponse("Invalid URL")


def booking(request):
    if request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        location = request.POST["location"].strip()
        id = request.POST["id"].strip()
        propert = Property.objects.get(id=int(id))
        try:
            b = Booking(name=name, phone=phone, email=email,
                        location=location, propert=propert)
            b.save()
            messages.success(
                request, 'Booking successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def rent(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="rent")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/rent.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def sale(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="sale")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/sale.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def land(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="sale")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/land.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def contact(request):
    if request.method == "GET":
        return render(request, 'main/nav/contact.html')
    elif request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        address = request.POST["address"].strip()
        message = request.POST["message"].strip()
        try:
            c = Contact(name=name, phone=phone, email=email,
                        address=address, message=message)
            c.save()
            messages.success(
                request, 'Your message sent successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def about(request):
    if request.method == "GET":
        return render(request, 'main/nav/about.html')
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def listing(request):
    if request.method == "GET":
        return render(request, 'main/forms/listing.html')
    elif request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        address = request.POST["address"].strip()
        region = request.POST["region"].strip()
        category = request.POST["property"].strip()
        try:
            l = Listings(name=name, phone=phone, email=email,
                         address=address, region=region, category=category)
            l.save()
            messages.success(
                request, 'Your message sent successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def search(request):
    if request.method == "POST":
        keyword = request.POST["keyword"].strip()
        region = request.POST["region"].strip()
        category = request.POST["category"].strip()
        max_price = request.POST["max_price"].strip()

        try:
            posts = Property.objects.filter(
                name__icontains=keyword, region__name__icontains=region, category__name__icontains=category)[:12]
            num = posts.count()
            context = {
                "posts": posts,
                "num": num,
            }
            return render(request, 'main/nav/searchResults.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")

templates/main/forms/booking.html
<div class="container">
  <button
    type="button"
    class="w-100 btn-2"
    data-bs-toggle="modal"
    data-bs-target="#staticBackdrop"
  >
    Book a Viewing for the property
  </button>

  <!-- Modal -->
  <div
    class="modal w-100 fade my-5 py-4"
    id="staticBackdrop"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-labelledby="staticBackdropLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header btn-primary">
          <h5 class="modal-title" id="staticBackdropLabel">
            Book a Viewing for the property
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url 'main:booking' %}">
            {% csrf_token %}
            <div class="mb-3">
              <input
                type="hidden"
                class="form-control"
                name="id"
                value="{{post.id}}"
                required
              />
            </div>
            <div class="mb-3">
              <label class="form-label">Full Name</label>
              <input type="text" class="form-control" name="name" required />
            </div>
            <div class="mb-3">
              <label class="form-label">Mobile Phone</label>
              <input type="number" class="form-control" name="phone" required />
            </div>
            <div class="mb-3">
              <label class="form-label">Email address</label>
              <input type="email" class="form-control" name="email" required />
            </div>
            <div class="mb-3">
              <label class="form-label">Your Location</label>
              <input
                type="text"
                class="form-control"
                name="location"
                required
              />
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

templates/main/forms/listing.html
{% extends 'main/base.html' %} {% load static %} {% block content %}
<div class="container mt-3 pb-4">
  <h4 class="text-center headings mt-4">List your property with us</h4>
  <form class="row g-3 mt-4" method="POST" action="{% url 'main:listing' %}">
    {% csrf_token %}
    <div class="col-md-4">
      <label class="form-label">Full Name</label>
      <input type="text" name="name" class="form-control" required />
    </div>
    <div class="col-md-4">
      <label class="form-label">Mobile Number</label>
      <input type="number" name="phone" class="form-control" required />
    </div>
    <div class="col-md-4">
      <label class="form-label">Email Address</label>
      <input type="email" name="email" class="form-control" required />
    </div>
    <div class="col-md-4">
      <label class="form-label">Address</label>
      <input type="text" name="address" class="form-control" required />
    </div>
    <div class="col-md-4">
      <label class="form-label">Region</label>
      <input
        type="text"
        name="region"
        class="form-control"
        required
        placeholder="NAIROBI, BURUBURU"
      />
    </div>
    <div class="col-md-4">
      <label class="form-label">Property Type</label>
      <input
        type="text"
        name="property"
        class="form-control"
        required
        placeholder="Apartment, Home,  Office Block, or Land"
      />
    </div>

    <div class="col-12 text-center py-4">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
<div class="container-fluid services-bg">
  {% include 'main/incl/services.html' %}
</div>

{% endblock content %}

templates/main/forms/searchForm.html
<!-- Search form -->
<div class="container mt-3">
  <form
    class="row g-3 mt-4 align-items-center"
    method="POST"
    action="{% url 'main:search' %}"
  >
    {% csrf_token %}
    <div class="col-sm-3 my-1">
      <label class="visually-hidden">Key Word</label>
      <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
      <input
        type="text"
        class="form-control"
        name="keyword"
        placeholder="Enter Keyword"
        required
      />
    </div>
    <div class="col-sm-2 my-1">
      <label class="visually-hidden">Region</label>
      <input
        type="text"
        class="form-control"
        name="region"
        placeholder="Enter Region"
        required
      />
    </div>
    <div class="col-sm-2 my-1">
      <label class="visually-hidden">Property</label>
      <select class="form-select" name="category" required>
        <option selected>Select Property...</option>
        <option value="Sale">Sale</option>
        <option value="Rent">Rental</option>
        <option value="Land">Land</option>
      </select>
    </div>
    <div class="col-sm-3 my-1">
      <label class="visually-hidden">Max price</label>
      <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
      <input
        type="number"
        class="form-control"
        name="max_price"
        placeholder="Maximum Price KSH"
        required
      />
    </div>
    <div class="col-auto my-1">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </form>
</div>