main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('properties/<str:slug>/', detailedview, name='detailedview'),
    path('property-view-booking/', booking, name='booking'),
    path('property-for-rent/', rent, name='rent'),
    path('property-for-sale/', sale, name='sale'),
    path('land-for-sale/', land, name='land'),
    path('contact-us/', contact, name='contact'),
    path('about-us/', about, name='about'),
    path('list-your-property/', listing, name='listing'),
    path('properties-search/', search, name='search'),
]

property/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

admin.site.site_header = 'Rolproperties admin'
admin.site.site_title = 'Rolproperties admin'
admin.site.index_title = 'Rolproperties administration'

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from autoslug import AutoSlugField


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Listings(models.Model):
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='name')
    email = models.EmailField(max_length=30)
    address = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    category = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    date_posted = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


CATEGORIES = (
    ("Sale", "Sale"),
    ("Rent", "Rent"),
    ("Lease", "Lease"),
)

UNITS = (
    (" ", "No Units"),
    ("K", "K"),
    ("M", "M"),

)


class Property(models.Model):
    '''property model'''
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='name', unique=True)
    seller = models.CharField(default="Seller", max_length=100)
    date_posted = models.DateField(auto_now_add=True)
    rooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    bedrooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    bathrooms = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    sqfts = models.DecimalField(
        decimal_places=0, max_digits=5, blank=True, null=True)
    size = models.CharField(default="For Land only", max_length=100, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="properties")
    type_for = models.CharField(choices=CATEGORIES, max_length=10)
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE, related_name="properties")
    price = models.IntegerField()
    price_units = models.CharField(max_length=10, choices=UNITS)
    short_description = models.CharField(max_length=60)
    description = models.TextField()
    featured = models.BooleanField(default=False)
    image_1 = models.ImageField(upload_to="images")
    image_2 = models.ImageField(upload_to="images")
    image_3 = models.ImageField(upload_to="images")
    image_4 = models.ImageField(upload_to="images")
    image_5 = models.ImageField(upload_to="images")
    image_6 = models.ImageField(upload_to="images")

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=50)
    message = models.TextField(max_length=255)
    date_posted = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name


class Booking(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=15)
    location = models.CharField(max_length=50)
    date_posted = models.DateField(auto_now_add=True)
    propert = models.ForeignKey(
        Property, on_delete=models.CASCADE, related_name="properties")

    class Meta:
        ordering = ('-date_posted', '-id')

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import *

# Create your views here.


def index(request):
    if request.method == "GET":
        # try:
        posts = Property.objects.all()[:6]
        slides = Property.objects.filter(featured=True)[:3]
        context = {
            "posts": posts,
            "slides": slides,
        }
        return render(request, 'main/nav/home.html', context)
        # except:
        #     messages.error(
        #         request, 'Something went wrong, kindly try again!!!')
        #     return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def detailedview(request, slug):
    if request.method == "GET":
        try:
            post = Property.objects.get(slug=slug)
            context = {
                "post": post,
            }

            return render(request, 'main/incl/details.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")

    else:
        return HttpResponse("Invalid URL")


def booking(request):
    if request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        location = request.POST["location"].strip()
        id = request.POST["id"].strip()
        propert = Property.objects.get(id=int(id))
        try:
            b = Booking(name=name, phone=phone, email=email,
                        location=location, propert=propert)
            b.save()
            messages.success(
                request, 'Booking successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def rent(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="rent")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/rent.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def sale(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="sale")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/sale.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def land(request):
    if request.method == "GET":
        try:
            posts = Property.objects.filter(
                category__name__icontains="sale")[:6]
            context = {
                "posts": posts,
            }
            return render(request, 'main/nav/land.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def contact(request):
    if request.method == "GET":
        return render(request, 'main/nav/contact.html')
    elif request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        address = request.POST["address"].strip()
        message = request.POST["message"].strip()
        try:
            c = Contact(name=name, phone=phone, email=email,
                        address=address, message=message)
            c.save()
            messages.success(
                request, 'Your message sent successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def about(request):
    if request.method == "GET":
        return render(request, 'main/nav/about.html')
    elif request.method == "POST":
        return HttpResponse("Invalid URL")
    else:
        return HttpResponse("Invalid URL")


def listing(request):
    if request.method == "GET":
        return render(request, 'main/forms/listing.html')
    elif request.method == "POST":
        name = request.POST["name"].strip()
        phone = request.POST["phone"].strip()
        email = request.POST["email"].strip()
        address = request.POST["address"].strip()
        region = request.POST["region"].strip()
        category = request.POST["property"].strip()
        try:
            l = Listings(name=name, phone=phone, email=email,
                         address=address, region=region, category=category)
            l.save()
            messages.success(
                request, 'Your message sent successfully!')
            return redirect("main:index")
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")


def search(request):
    if request.method == "POST":
        keyword = request.POST["keyword"].strip()
        region = request.POST["region"].strip()
        category = request.POST["category"].strip()
        max_price = request.POST["max_price"].strip()

        try:
            posts = Property.objects.filter(
                name__icontains=keyword, region__name__icontains=region, category__name__icontains=category)[:12]
            num = posts.count()
            context = {
                "posts": posts,
                "num": num,
            }
            return render(request, 'main/nav/searchResults.html', context)
        except:
            messages.error(
                request, 'Something went wrong, kindly try again!!!')
            return redirect("main:index")
    else:
        return HttpResponse("Invalid URL")

templates/main/incl/bootnav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary topnav">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}">
      <img
        src="{% static 'main/images/logo.jpeg' %}"
        alt="Rol Properties Logo"
        class="d-inline-block align-text-top rounded"
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 topul">
        <li class="nav-item topli">
          <a
            class="nav-link toplink"
            aria-current="page"
            href="{% url 'main:index' %}"
            >Home</a
          >
        </li>
        <li class="nav-item topli">
          <a
            class="nav-link toplink"
            aria-current="page"
            href="{% url 'main:about' %}"
            >About Us</a
          >
        </li>
        <li class="nav-item topli">
          <a class="nav-link toplink" href="{% url 'main:sale' %}"
            >Properties For Sale</a
          >
        </li>
        <li class="nav-item topli">
          <a class="nav-link toplink" href="{% url 'main:rent' %}"
            >Properties For Rent</a
          >
        </li>
        <li class="nav-item topli">
          <a class="nav-link toplink" href="#">Land</a>
        </li>
        <li class="nav-item topli">
          <a class="nav-link toplink" href="{% url 'main:contact' %}"
            >Contact Us</a
          >
        </li>
      </ul>

      <span class="navbar-text">
        <a href="{% url 'main:listing' %}" class="btn-1">List Property</a>
      </span>
    </div>
  </div>
</nav>

templates/main/incl/details.html
{% extends 'main/base.html' %} {% load static %} {% block content %}
<div class="container text-center py-4 detailed">
  <div class="container">
    <!-- Top bar -->
    <div class="row my-2 py-2">
      <div class="col-md-12">
        <h4 class="text-center">{{post.name}}</h4>
      </div>
    </div>
    <div class="row my-2 py-2">
      <div class="col-md-12">
        <h4 class="text-center">
          KSH {{post.price}} {{post.price_units}} | For {{post.type_for}} | {{post.region}}
        </h4>
      </div>
    </div>
  </div>
  <!-- Images -->
  <div class="container">
    <div class="row my-2 py-2">
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_1.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_2.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_3.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
    </div>
    <div class="row my-2 py-2">
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_4.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_5.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
      <div class="col-md-4">
        <div class="card text-center">
          <img
            src="{{post.image_6.url}}"
            class="card-img-top detailed-image"
            alt="property image"
          />
        </div>
      </div>
    </div>
  </div>
  <!-- Short intro  -->
  <div class="row my-3 py-3">
    <div class="col-md-12 d-flex justify-content-evenly">
      <i class="fa fa-bed" aria-hidden="true"></i>
      <span><p>{{post.rooms}} Rooms</p></span>
      <i class="fa fa-bed" aria-hidden="true"></i>
      <span><p>{{post.bedrooms}} Bedrooms</p></span>
      <i class="fa fa-bath" aria-hidden="true"></i
      ><span><p>{{post.bathrooms}} Bathrooms</p></span>
      <i class="fa fa-area-chart" aria-hidden="true"></i
      ><span><p>{{post.sqfts}} SqFts</p></span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h5 class="text-start">Features</h5>
      <hr />
      <div class="d-flex">
        <p class="px-2">Water</p>
        <p class="px-2">Pets allowed</p>
        <p class="px-2">Sewer</p>
        <p class="px-2">Electricity</p>
        <p class="px-2">Security</p>
      </div>
    </div>
  </div>
  <!-- description  -->
  <div class="row my-3 py-3">
    <div class="col-md-12">
      <p>{{post.description}}</p>
    </div>
  </div>

  <!-- Book View form -->
  <!-- Book a Viewing for the property -->
  <div class="container">
    <div>{% include 'main/forms/booking.html' %}</div>
  </div>
</div>
{% endblock content %}

templates/main/incl/lower-footer.html
<div class="row mt-4 mx-0 myfooter">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <p class="text-center"></p>
    <p class="text-center">
      Copyright &copy; ROL properties , 2021 | All Rights Reserved.
    </p>
  </div>
  <div class="col-md-2 text-center">
    <p>Designed & Built by: amosndonga@gmail.com</p>
  </div>
</div>

templates/main/incl/navigation.html
<div class="container-fluid topnav" id="scroll">
  <ul class="topul">
    <li class="topli">
      <a href="{% url 'main:index' %}" class="toplink">Home</a>
    </li>
    <li class="topli">
      <a href="{% url 'main:sale' %}" class="toplink">Property For Sale</a>
    </li>
    <li class="topli">
      <a href="{% url 'main:rent' %}" class="toplink">Property For Rent</a>
    </li>
    <li class="topli">
      <a href="{% url 'main:land' %}" class="toplink">Land</a>
    </li>
    <li class="topli">
      <a href="{% url 'main:contact' %}" class="toplink">Contact</a>
    </li>
  </ul>

  <p>Call US: +254-7000000</p>
  <a href="#" class="btn-1">Sign In</a>
</div>

templates/main/incl/services.html
{% load static %}
<div class="container my-4 py-4">
  <h4 class="text-center services-header">How we help people?</h4>
  <div class="row my-4 py-4 text-center services-inner">
    <div class="col-md-4">
      <img src="{% static 'main/images/home.svg' %}" class="my-3" alt="image" />
      <h4>Home & Appartment</h4>
      <p class="mt-2 pt-2">We help you sell, rent or buy home and apartments</p>
    </div>
    <div class="col-md-4">
      <img
        src="{% static 'main/images/office.svg' %}"
        class="my-3"
        alt="image"
      />
      <h4>Office</h4>
      <p class="mt-2 pt-2">We help you rent or sell offices</p>
    </div>
    <div class="col-md-4">
      <img src="{% static 'main/images/home.svg' %}" class="my-3" alt="image" />
      <h4>Land</h4>
      <p class="mt-2 pt-2">We help you sell, buy or lease land</p>
    </div>
  </div>
</div>

templates/main/incl/slides.html
<div class="container">
  <div
    id="carouselExampleCaptions"
    class="carousel slide my-3 py-3 home_bg1"
    data-bs-ride="carousel"
  >
    <div class="carousel-indicators">
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="0"
        class="active"
        aria-current="true"
        aria-label="Slide 1"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="1"
        aria-label="Slide 2"
      ></button>
      <button
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide-to="2"
        aria-label="Slide 3"
      ></button>
    </div>
    <div class="carousel-inner">
      {% for slide in slides %}
      <div
        class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}"
      >
        <img
          src="{{slide.image_1.url}}"
          class="d-block w-100 slide_images"
          alt="featured properties images"
        />
        <div class="carousel-caption d-md-block">
          <h3 class="pt-5 top-intro featured">
            {{slide.bedrooms}} BedRooms - {{slide.bathrooms}} BathRooms -
            {{slide.sqfts}} Sq Ft
          </h3>
          <h1 class="mt-4 top-title featured">{{slide.name}}</h1>
          <h3 class="mt-4 top-price featured">
            KSH {{slide.price}}{{slide.price_units}}
          </h3>
          <h5 class="my-0 py-2">For {{slide.category}}</h5>
          <h5 class="my-0 py-2">{{slide.region}}</h5>
          <a
            href="{% url 'main:detailedview' slug=slide.slug %}"
            class="mt-4 btn-2"
            >View Property</a
          >
        </div>
      </div>
      {% endfor %}
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleCaptions"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

templates/main/incl/top-footer.html
{% load static %}
<div class="container mb-5 pb-5">
  <div class="row mt-5">
    <div class="col-md-3 mt-3">
      <div class="d-flex mb-2">
        <img
          src="{% static 'main/images/logo.jpeg' %}"
          alt="Rol Properties Logo"
          class="rounded"
        />
      </div>
      <p>For all your needs</p>
      <div class="d-flex social-icons">
        <i class="bi bi-instagram mx-2 icons-spin"></i>
        <i class="bi bi-facebook mx-2 icons-spin"></i>
        <i class="bi bi-twitter mx-2 icons-spin"></i>
        <i class="bi bi-youtube mx-2 icons-spin"></i>
      </div>
    </div>
    <div class="col-md-3 mt-3">
      <h4>Navigation</h4>
      <p>
        <a href="{% url 'main:index' %}" class="footer-link">Home</a>
      </p>
      <p>
        <a href="{% url 'main:about' %}" class="footer-link">About Us</a>
      </p>
      <p>
        <a href="{% url 'main:sale' %}" class="footer-link"
          >Properties For Sale</a
        >
      </p>
      <p>
        <a href="{% url 'main:rent' %}" class="footer-link"
          >Properties For Rent</a
        >
      </p>
      <p>
        <a href="#" class="footer-link">Land</a>
      </p>
    </div>
    <div class="col-md-3 mt-3">
      <h4>Services</h4>
      <p>Real Estate</p>
      <p>Property Management</p>
    </div>
    <div class="col-md-3 mt-3">
      <h4>Contacts Us</h4>
      <p>Sameer Park Mombasa Road,</p>
      <p>P.O. Box 369 – 00100 GPO</p>
      <p>Nairobi, Kenya</p>
      <p>Tel: +254 786 995077</p>
      <p>info@rolproperties.com</p>
    </div>
  </div>
</div>